INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Andres', 'Guzmán', 'profesor@ideario.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Mr. John', 'Doe', 'johndoe@gmail.com', '2018-03-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Linus', 'Torvalds', 'linustorvalds@gmail.com', '2018-02-11');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Rasmus', 'Lerdorf', 'Rammus@nose.com', '2018-12-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Erich', 'Gamma', 'Eric@beta.com', '2018-05-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Richard', 'Helm', 'richard@helm.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Ralph', 'Wiggum', 'ralphy@wiggum.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('John', 'Thompson', 'tom@johnson.com', '2019-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Dr. James', 'Gosling', 'james@rocket.com', '2018-02-21');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Samus', 'Aran', 'samus@aria.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Luigi', 'Shroom', 'luigi@nintendo.com', '2018-07-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Jade', 'Doe', 'jadedoe@gmail.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Andres', 'Guzmán', 'profesor@1ideario.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Mr. John', 'Doe', 'johndoe@1gmail.com', '2018-03-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Linus', 'Torvalds', 'linustorvalds@1gmail.com', '2018-02-11');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Rasmus', 'Lerdorf', 'Rammus@1nose.com', '2018-12-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Erich', 'Gamma', 'Eric@1beta.com', '2018-05-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Richard', 'Helm', 'richard@1helm.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Ralph', 'Wiggum', 'ralphy@1wiggum.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('John', 'Thompson', 'tom@1johnson.com', '2019-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Dr. James', 'Gosling', 'james@1rocket.com', '2018-02-21');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Samus', 'Aran', 'samus@1aria.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Luigi', 'Shroom', 'luigi@1nintendo.com', '2018-07-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Jade', 'Doe', 'jadedoe@1gmail.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Andres', 'Guzmán', 'profesor@2ideario.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Mr. John', 'Doe', 'johndoe@2gmail.com', '2018-03-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Linus', 'Torvalds', 'linustorvalds@2gmail.com', '2018-02-11');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Rasmus', 'Lerdorf', 'Rammus@2nose.com', '2018-12-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Erich', 'Gamma', 'Eric@2beta.com', '2018-05-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Richard', 'Helm', 'richard@2helm.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Ralph', 'Wiggum', 'ralphy@2wiggum.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('John', 'Thompson', 'tom@2johnson.com', '2019-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Dr. James', 'Gosling', 'james@2rocket.com', '2018-02-21');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Samus', 'Aran', 'samus@2aria.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Luigi', 'Shroom', 'luigi@2nintendo.com', '2018-07-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Jade', 'Doe', 'jadedoe@2gmail.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Andres', 'Guzmán', 'profesor@3ideario.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Mr. John', 'Doe', 'johndoe@3gmail.com', '2018-03-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Linus', 'Torvalds', 'linustorvalds@3gmail.com', '2018-02-11');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Rasmus', 'Lerdorf', 'Rammus@3nose.com', '2018-12-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Erich', 'Gamma', 'Eric@3beta.com', '2018-05-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Richard', 'Helm', 'richard@3helm.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Ralph', 'Wiggum', 'ralphy@3wiggum.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('John', 'Thompson', 'tom@3johnson.com', '2019-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Dr. James', 'Gosling', 'james@3rocket.com', '2018-02-21');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Samus', 'Aran', 'samus@3aria.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Luigi', 'Shroom', 'luigi@3nintendo.com', '2018-07-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Jade', 'Doe', 'jadedoe@3gmail.com', '2018-02-01');